Module6 task1
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #11
Opened 2022-01-04 22:27 UTC by CheapSellsword

2022-01-04 23:15 UTC, CheapSellsword commented on src/view/smart-view.js
> +      this.restoreHandlers();
Проблемы:
1. При переходе к другому попапу и возвращении обратно восстанавливаются не все ивент листенеры (эмодзи не выбираются).
2. Чтобы при перерисовке восстановить листенеры на кнопках попапа, пришлось передать их из презентера в `film-popup-view`. 

Есть ли смысл делать полную перерисовку попапа по логике из лайва, или можно сделать `appendChild` нужного эмодзи по клику, а при ресете удалить этот элемент?

2022-01-04 23:15 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +    const image = this.element.querySelector(`label[for=${evt.target.id}]`).children[0];
При клике на эмодзи, вместо картинки вставляется строка 'imageElement'. Как я понял, перед вставкой объект превращается в строку, но я не понимаю, как это можно здесь исправить.

2022-01-07 10:08 UTC, NiyazGaripov commented on src/view/smart-view.js
> +      this.restoreHandlers();
@CheapSellsword 
Параметр `addPopupListeners`, который используется в конструкторе класса `FilmPopupView`, всегда `undefined`.
Далее в конструкторе `this.#popupListeners = addPopupListeners;`. Соответственно `this.#popupListeners` будет равняться `undefined`. Далее в методе `restoreHandlers`  на 196 строке по факту ничего не происходит. Так как `this.#popupListeners = undefined`.

Кнопки Add to watchlist, Already watched, Add to favorites работают корректно.

Эмодзи не выбираются из-за того, что некорректно работает метод `emojiChangeHandler`.

> Есть ли смысл делать полную перерисовку попапа по логике из лайва, или можно сделать appendChild нужного эмодзи по клику, а при ресете удалить этот элемент?

Возможно реализация с полной перерисовкой попапа, либо с перерисовкой только блока добавления нового комментария. Для реализации второго варианта нужно блок добавления нового комментария вынести в отдельный класс. Отнаследоваться от `SmartView `. И реализовать в классе обработчики на выбор эмодзи, на ввод комментария, на восстановление обработчиков.

2022-01-07 11:21 UTC, NiyazGaripov requested changes

2022-01-07 11:21 UTC, NiyazGaripov commented on src/view/smart-view.js
> +      const prevScrollPosition = (window.pageYOffset !== undefined) ? window.pageYOffset : (document.documentElement || document.body.parentNode || document.body).scrollTop;
@CheapSellsword
Усложняешь. Возможно использовать [scrollTop](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop)

2022-01-07 12:37 UTC, CheapSellsword commented on src/view/smart-view.js
> +      this.restoreHandlers();
> Параметр `addPopupListeners`, который используется в конструкторе класса `FilmPopupView`, всегда `undefined`.

Я случайно сделал коммит, где `film-presenter.js` был сохранен в состоянии, когда в `FilmPopupView` не был передан второй параметр. Прощу прощения за невнимательность.

2022-01-09 04:59 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +      // isEmojiChecked: evt.target.id,
Не могу разобраться с принципом корректной передачи аттрибута `checked` нужному эмодзи.

2022-01-09 05:07 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +    if (evt.target === 'Cmd' && evt.target === 'Enter' || evt.target === 'Command' && evt.target === 'Enter' || evt.target === 'Ctrl' && evt.target === 'Enter') {
Попытался сделать `enum` по образцу из интернета:
export const ENUM = {};
ENUM.keys = {
  ENTER: 13,
  ESCAPE: 27,
};

Не удалось использовать его значения - нажатия на клавиши не работают. Читал про `enum`, но не понял, для чего он здесь нужен?

2022-01-09 05:20 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +      const chosenEmoji = this.element.querySelector('.film-details__add-emoji-label');
Добавил очистку поля ввода по отправке комментария. Если после отправки комментария с текстом нажать на эмодзи, то текст вернется в поле ввода. Подозреваю, что функция `parseDataToFilm` должна быть сложнее: 
1. В массив комментариев должен добавляться только что созданный
2. Данные, касающиеся нового комментария, должны обнуляться

2022-01-09 13:29 UTC, NiyazGaripov commented on src/view/film-popup-view.js
> +    if (evt.target === 'Cmd' && evt.target === 'Enter' || evt.target === 'Command' && evt.target === 'Enter' || evt.target === 'Ctrl' && evt.target === 'Enter') {
@CheapSellsword 
`Enum` это перечисление. Ты уже его применял `RANKS`, `MODE` и т.д.

```
export const EvtKey = {
  ESCAPE: 'Escape',
  ESC: 'Esc',
  ENTER: 'Enter',
};
```

2022-01-09 14:39 UTC, NiyazGaripov commented on src/view/film-popup-view.js
> +      // isEmojiChecked: evt.target.id,
@CheapSellsword 
Для начала реализуй функцию, которая будет возвращать список эмодзи для выбора.
Вместо вот этой разметки 

```
<input class="film-details__emoji-item visually-hidden" ${isChecked} name="comment-emoji" type="radio" id="emoji-smile" value="smile">
<label class="film-details__emoji-label" for="emoji-smile">
  <img src="./images/emoji/smile.png" width="30" height="30" alt="emoji">
</label>

<input class="film-details__emoji-item visually-hidden" ${isChecked} name="comment-emoji" type="radio" id="emoji-sleeping" value="sleeping">
<label class="film-details__emoji-label" for="emoji-sleeping">
  <img src="./images/emoji/sleeping.png" width="30" height="30" alt="emoji">
</label>

<input class="film-details__emoji-item visually-hidden" ${isChecked} name="comment-emoji" type="radio" id="emoji-puke" value="puke">
<label class="film-details__emoji-label" for="emoji-puke">
  <img src="./images/emoji/puke.png" width="30" height="30" alt="emoji">
</label>

<input class="film-details__emoji-item visually-hidden" ${isChecked} name="comment-emoji" type="radio" id="emoji-angry" value="angry">
<label class="film-details__emoji-label" for="emoji-angry">
  <img src="./images/emoji/angry.png" width="30" height="30" alt="emoji">
</label>
```

используй данную функцию.

Реализовать данную функцию можно несколькими способами.
Один из вариантов:
1. Создаешь константу со списком эмодзи `['smile', 'sleeping', 'puke', 'angry'];`
2. При помощи метода `map` итерируешься по массиву и для каждой эмодзи передаешь `callback`
3. Функция принимает в качестве параметра название эмодзи и вставляет в разметку. Внутри функции проверяем `${isEmojiChecked === emoji ? checked : ''}` (`isEmojiChecked` может быть `evt.target.id` или `evt.target.value`).

Т.е. сравниваешь выбранную эмодзи с эмодзи которая взята из массива эмодзи. Если они равны, то ставишь атрибут `checked`

2022-01-09 15:33 UTC, NiyazGaripov requested changes

2022-01-09 15:33 UTC, NiyazGaripov commented on src/view/film-popup-view.js
> +      const chosenEmoji = this.element.querySelector('.film-details__add-emoji-label');
@CheapSellsword 
У тебя в состоянии остаётся информация с выбранным эмодзи и написанным текстом.
Чтобы убедиться в этом, можешь дебагер поставить.

Из-за этого в методе `parseDataToFilm`  `film.isText` будет равен `true`. 
Соответственно код в этом условии `if (!film.isText)` не отработает.

И ещё раз проверь работу методов `updateTextData` и `updateData` с дебагером

2022-01-13 08:15 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +      const chosenEmoji = this.element.querySelector('.film-details__add-emoji-label');
@NiyazGaripov 
Не удалось исправить. 
Я не смог разобраться как проверить методы с дебагером :(

2022-01-13 10:42 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +      this._callback.formSubmit = this.updateData(FilmPopupView.parseDataToFilm(this._data));
Удалось, наконец, решить проблему с инпутом

2022-01-13 19:18 UTC, NiyazGaripov requested changes

2022-01-13 19:18 UTC, NiyazGaripov commented on src/view/film-popup-view.js
> +      this._callback.formSubmit = this.updateData(FilmPopupView.parseDataToFilm(this._data));
@CheapSellsword 
Логика не верная. 
`this._callback` это объект, в который записываются callback-функции. Эти callback-функции ты вызываешь в нужный для тебя момент.

Пример вызова callback-функции в методе выше:
```
#closePopupClickHandler = (evt) => {
  evt.preventDefault();
  this._callback.closePopupClick();
}
```
`this._callback` - объект. `closePopupClick` - метод объекта. 

Как создаётся данный метод.
В презентере фильма вызывается метод `setClosePopupClickHandler`. В данный метод передаётся callback-функция `this.#closePopupClickHandler`.
Соответственно в `film-popup-view.js` метод `setClosePopupClickHandler` принимает callback-функцию `this.#closePopupClickHandler` и записывает в `this._callback.closePopupClick`. 
```
  setClosePopupClickHandler = (callback) => {
    this._callback.closePopupClick = callback;
    this.element.querySelector('.film-details__close-btn').addEventListener('click', this.#closePopupClickHandler);
  }
```
А дальше в `#closePopupClickHandler`  callback-функция вызывается.

Теперь возвращаясь к  ` this._callback.formSubmit = this.updateData(FilmPopupView.parseDataToFilm(this._data));`
`this._callback.formSubmit` равен `undefined`. 
`this._callback.formSubmit` нужно вызывать. Аналогично вышеописанному сценарию для `this._callback.closePopupClick`.

1. В `film-presenter.js`  создай callback-функцию. В данной функции должен вызываться this.#changeData с обновлённым состоянием. К примеру
```
#handleNewCommentsSubmit = () => {
  this.#changeData({...this.#film});
}
```
2. В `film-presenter.js` вызови метод `setFormSubmitHandler` класса `FilmPopupView` и передай в этот метод `#handleNewCommentsSubmit`
```
 this.#filmPopupComponent.setFormSubmitHandler(this.#handleNewCommentsSubmit);
```
3. В `film-popup-view.js` переданная callback-функция записывается в `this._callback.formSubmit`. А дальше тебе нужно её вызвать и передать обновлённое состояние.
```
#formSubmitHandler = (evt) => {
  if (evt.key === EvtKey.ENTER && (evt.ctrlKey || evt.metaKey)) {
    evt.preventDefault();
    this._callback.formSubmit(FilmPopupView.parseDataToFilm(this._data));
  }
};
```

2022-01-13 19:18 UTC, NiyazGaripov commented on src/view/film-popup-view.js
> +                    <div class="film-details__add-emoji-label">${isEmoji ? film.emoji : ''}</div>
@CheapSellsword 
Если будешь использовать `isEmoji: '', isText: '', isEmojiChecked: ''`
тут будет просто `${isEmoji}`

2022-01-15 06:58 UTC, merged