Module6 task2
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #12
Opened 2022-01-06 03:22 UTC by CheapSellsword

2022-01-06 03:25 UTC, CheapSellsword commented on src/utils/dates-and-time.js
> +  if (minutesDifference < MINUTE_DIFFERENCE_LIMIT && minutesDifference > SINGLE_TIME_UNIT_LIMIT && minutesDifference >= A_FEW_MINUTES_LIMIT) {
В документации dayjs я видел humanize (уже после того как я написал логику), но не понял, как установить плагины, чтобы этим пользоваться

2022-01-15 09:59 UTC, CheapSellsword commented on src/consts.js
Этот коммит должен был называться "Настроит отображение времени в человеческом формате". Пока разбирался с ветками и как их мерджить, закоммитил его с некорректным названием "-"

2022-01-15 14:57 UTC, NiyazGaripov commented on src/utils/dates-and-time.js
> +    const hours = Math.floor(num / 60);
@CheapSellsword 
Для 60 используй константу
[Критерий Б31](https://up.htmlacademy.ru/ecmascript/16/criteries#b31)

2022-01-15 14:57 UTC, NiyazGaripov commented on src/consts.js
@CheapSellsword 
Факультативно про Git. Чтобы понимать Git flow

1. https://git-scm.com/book/en/v2 - документация
2. https://learngitbranching.js.org/?locale=en_EN - интерактивный курс
3. https://githowto.com/  - интерактивный курс

2022-01-15 15:15 UTC, NiyazGaripov commented on src/utils/dates-and-time.js
> +  if (minutesDifference < MINUTE_DIFFERENCE_LIMIT && minutesDifference > SINGLE_TIME_UNIT_LIMIT && minutesDifference >= A_FEW_MINUTES_LIMIT) {
@CheapSellsword 
Устанавливать плагины не нужно.
Их нужно импортировать и расширить dayjs данными плагинами.
```
import durationPlugin from 'dayjs/plugin/duration';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(durationPlugin);
dayjs.extend(relativeTime);
dayjs.duration(1, 'minutes').humanize(); // a minute
dayjs.duration(2, 'minutes').humanize(); // 2 minutes
dayjs.duration(24, 'hours').humanize();  // a day
```

2022-01-15 15:34 UTC, NiyazGaripov requested changes

2022-01-15 15:34 UTC, NiyazGaripov commented on src/utils/dates-and-time.js
> +  } else if (minutesDifference === SINGLE_TIME_UNIT_LIMIT) {
@CheapSellsword 
Лучше данную портянку с `else if` заменить на [humanize](https://day.js.org/docs/en/durations/humanize) из dayjs. 
Как с этим работать описал выше.
Либо реализовать подходящую структуру данных, чтобы избежать такого большого количества `else if`. К примеру использовать перечисление.

2022-01-17 17:41 UTC, merged