Module7 task1
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #13
Opened 2022-01-16 10:49 UTC by CheapSellsword

2022-01-16 21:58 UTC, CheapSellsword commented on src/view/film-popup-view.js
> +    if (evt.key === EvtKey.ENTER && (evt.ctrlKey || evt.metaKey) && this.#newComment.emoji !== '' && this.#newComment.emoji !== null && this.#newComment.emoji !== undefined && this.#newComment.text !
Можно ли укоротить условие?

2022-01-16 22:14 UTC, CheapSellsword commented
Вопросы:
1. При клике на цифры фильтров всё ломается. Нужно на них навесить отдельные обработчики?
2. При работе метода `reset` в `film-popup-view` на попап навешиваются ивент листенеры на кнопки два раза - от презентера и от попапа. Стоит ли писать отдельный метод `updateData` для `reset`?
3. Почему прослушивание события `change` нельзя делегировать форме с эмодзи?

2022-01-18 22:00 UTC, NiyazGaripov commented
@CheapSellsword 
> 2. При работе метода reset в film-popup-view на попап навешиваются ивент листенеры на кнопки два раза - от презентера и от попапа. Стоит ли писать отдельный метод updateData для reset?

Нет достаточно удалять события. Если зайдешь на вкладку Event Listeners в devtools и попробуешь покликать по кнопкам в попапе, то увидишь, что у тебя постоянно события добавляются. 

И по идее достаточно одного обработчика на кнопку.

2022-01-18 22:47 UTC, NiyazGaripov requested changes

2022-01-22 20:09 UTC, NiyazGaripov requested changes
Ещё одни момент, при добавлении нового комментария скролл сбрасывается и происходит прокрутка вверх

2022-01-22 20:09 UTC, NiyazGaripov commented on src/presenter/film-collection-presenter.js
> +            this.#presenters.find((presenter) => presenter.id === update.id).removeDocumentEventListeners();
@CheapSellsword 
Чтобы не дублировать if можно в цикле проходиться по презентерам и вызывать метод `removeDocumentEventListeners`

2022-01-23 13:38 UTC, CheapSellsword commented on src/presenter/film-collection-presenter.js
> +            this.#presenters.find((presenter) => presenter.id === update.id).removeDocumentEventListeners();
Избежать двойного условия не получилось после того как я исправил скролл

2022-01-23 18:48 UTC, merged