Меняй-удаляй (часть 2)
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #14
Opened 2022-01-21 19:26 UTC by CheapSellsword

---
:mortar_board: [Меняй-удаляй (часть 2)](https://up.htmlacademy.ru/ecmascript/16/user/1827273/tasks/13)

:boom: https://htmlacademy-ecmascript.github.io/1827273-cinemaddict-16/14/

2022-01-27 23:34 UTC, CheapSellsword commented
Насчет 8 задания: я отправил 8.1 на проверку с выполненными заданиями 8.2 и доп. функциональностью. Как быть? Создать пуллреквесты для проверки?

2022-01-29 10:25 UTC, NiyazGaripov commented
@CheapSellsword 
> Насчет 8 задания: я отправил 8.1 на проверку с выполненными заданиями 8.2 и доп. функциональностью. Как быть? Создать пуллреквесты для проверки?

Да

2022-01-29 13:32 UTC, NiyazGaripov requested changes

2022-01-29 13:32 UTC, NiyazGaripov commented on src/view/stats-view.js
> +      case STATS_PERIODS[0].value:
@CheapSellsword 
При таком объявлении `STATS_PERIODS[0].value` ты привязываешь к последовательности в STATS_PERIODS. А если последовательность изменится, или добавятся ещё пункты.
Используй структуры данных.
К примеру 
```
const StatsPeriod = {
  ALL: 'all-time',
  TODAY: 'today',
  WEEK: 'week',
  MONTH: 'month',
  YEAR: 'year',
};
```
Можно ещё дальше пойти. К примеру 
```
const NameToDate = {
  TODAY: dayjs(),
  WEEK: dayjs().subtract(1, 'week'),
  MONTH: dayjs().subtract(1, 'month'),
  YEAR: dayjs().subtract(1, 'year'),
};
```
И на основе этих структур создавать фильтры для статистики. К примеру
```
  [StatsPeriod.ALL]: (films) => films.filter((film) => film),
  [StatsPeriod.TODAY]: (films) => films.filter((film) => dayjs(...).isSame(NameToDate.TODAY, 'day')),
  [StatsPeriod.WEEK]: (films) => films.filter((film) => dayjs(...).isBetween(NameToDate.WEEK, NameToDate.TODAY, 'week', '[]')),
```

и так далее

2022-01-30 12:30 UTC, NiyazGaripov requested changes

2022-01-30 12:30 UTC, NiyazGaripov commented on src/utils/dates-and-time.js
> +export const NameToDate = {
@CheapSellsword 
Нужно дать осмысленное название. Данное название дал для примера.

2022-01-30 13:19 UTC, merged