Добавит компоненты
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #3
Opened 2021-11-25 15:54 UTC by CheapSellsword

Есть пара вопросов:

Нужно ли сейчас отрисовывать всю страницу? Я следовал рекомендациям по разделу страницы на компоненты, и там, вроде как, не покрыта вся страница.

Пункт "компонент «Карточка фильма» отрисовывается в списке 5 раз." Я отрисовал одну карточку 5 раз, но не уверен, что правильно понял этот пункт.

2021-11-25 19:13 UTC, NiyazGaripov commented
@CheapSellsword 
> Нужно ли сейчас отрисовывать всю страницу? Я собирался, но засомневался, так как в рекомендациях по разделу страницы на компоненты, вроде как, не покрыта вся страница.

Лучше отрисовать всю страницу. Тебе осталось отрисовать секции Top rated и Most commented. 
> 7. Откройте в браузере файл public/index.html. Все компоненты должны быть корректно отрисованы. Для проверки сравните полученный результат с разметкой в директории markup.

Помнишь мы с тобой за референс брали страницу `list.html` , вот с ней нужно и сравнивать конечный результат.

> Пункт компонент «Карточка фильма» отрисовывается в списке 5 раз. Я отрисовал одну и ту же карточку 5 раз, но не уверен, что правильно понял этот пункт.

На данном этапе ты сделал правильно, отрисовав одну и ту же карточку. Моковые данные будем делать в задании 2-го раздела.

2021-11-25 19:56 UTC, NiyazGaripov requested changes

2021-11-25 19:56 UTC, NiyazGaripov commented on src/render.js
> +  BEFOREBEGIN: 'beforebegin',
@CheapSellsword 
Константы состоящие из нескольких слов принято разделять через нижнее подчёркивание `BEFORE_BEGIN`
Пример есть в [критерии Б5](https://up.htmlacademy.ru/ecmascript/16/criteries#b5)

2021-11-25 19:56 UTC, NiyazGaripov commented on src/view/film-card-view.js
> +  <a class="film-card__link">
@CheapSellsword 
Проверь все файлы в директории `view` на предмет поехавшей разметки. Должны быть соблюдены отступы и вложенность. Сейчас это незаметно, но в дальнейшем, когда будет динамическое добавление контента, из-за этого могут возникать мелкие и неприятные ошибки.
В данном случае у тебя тег `article` на одном уровне с тегом `a`, а в конце файла закрывающий тег `</article>` расположен на разных уровнях с открывающим тегом `<article>`

2021-11-25 19:56 UTC, NiyazGaripov commented on src/main.js
> +for (let i = 0; i < 5; i++) {
@CheapSellsword 
5 является «магическим значением»,
По [критерию Б31](https://up.htmlacademy.ru/ecmascript/16/criteries#b31) под такие значения нужно заводить константы.

Ещё рекомендую сделать отдельный файл для констант `consts.js` и хранить все перечисления и константы в этом файле.

2021-11-25 19:56 UTC, NiyazGaripov commented on src/render.js
> +export const renderTemplate = (container, template, place) => {
@CheapSellsword 
Параметру `place` задай значение по умолчанию.
К примеру, `AFTER_BEGIN` используется большее количество раз, чем остальные позиции. Поэтому его можно указать в качестве значения по умолчанию.

2021-11-26 16:39 UTC, CheapSellsword commented
Исправил указанные ошибки, последовал рекомендациям. Спасибо!

2021-11-26 18:22 UTC, NiyazGaripov requested changes

2021-11-26 18:22 UTC, NiyazGaripov commented on src/consts.js
> +const CARDS_REQUIRED = 5;
@CheapSellsword 
Название константы не передаёт смысл. 
Если нужна константа, в которой содержится количество чего-либо, используй комбинацию: сущность во множественном числе + count. 
К примеру `FILMS_COUNT`

2021-11-26 18:22 UTC, NiyazGaripov commented on src/main.js
> +// closest?
@CheapSellsword 
Нужно удалить комментарий. [Критерий Б18](https://up.htmlacademy.ru/ecmascript/16/criteries#b18)

2021-11-26 18:22 UTC, NiyazGaripov commented on src/main.js
>  // Мешающий попап!
@CheapSellsword 
Нужно удалить комментарий. [Критерий Б18](https://up.htmlacademy.ru/ecmascript/16/criteries#b18)

2021-11-27 11:36 UTC, CheapSellsword commented on src/main.js
> +renderTemplate(mainElement, createSortAndStatsBar(), RenderPosition.AFTER_BEGIN);
Да, это я понимаю, просто вписал это для себя, чтобы наглядно было)
Сейчас исправлю

2021-11-27 11:37 UTC, CheapSellsword commented on src/consts.js
> +const CARDS_REQUIRED = 5;
Хорошо, сделаю. Спасибо!

2021-11-27 12:28 UTC, merged

2021-11-27 13:08 UTC, NiyazGaripov reviewed
@CheapSellsword Отлично! Молодец)