Module3 task1
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #6
Opened 2021-12-07 18:05 UTC by CheapSellsword

2021-12-07 22:48 UTC, NiyazGaripov requested changes

2021-12-07 22:48 UTC, NiyazGaripov commented on src/render.js
> +  const newElement = document.createElement('div');
@CheapSellsword 
Нужно убрать `Element` из названия константы или начать использовать `Element` во всем проекте для всех переменных, которые хранят DOM-элементы.
[критерий Д6](https://up.htmlacademy.ru/ecmascript/16/criteries#d6)

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/filter-stats-view.js
> +export default class FiltersAndStatsBarView {
@CheapSellsword 
Название модуля должно соответствовать названию класса и содержимому 
[критерий Б27](https://up.htmlacademy.ru/ecmascript/16/criteries#b27)

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/sort-view.js
> +export default class FilmSortView {
@CheapSellsword 
Название модуля должно соответствовать названию класса и содержимому 
[критерий Б27](https://up.htmlacademy.ru/ecmascript/16/criteries#b27)

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/sort-view.js
> +    <li><a href="#" class="sort__button sort__button--active">Sort by default</a></li>
@CheapSellsword 
Замени повторяющуюся разметку на функцию. 
Функцию размести выше этой функции.
Создай массив с типами сортировки. 
В функции `createSortTemplate` проходись (используй метод map) по этому массиву и у каждого элемента вызывай функцию, которая возвращает разметку элемента сортировки

```
const createSortItemTemplate = (type, isActive) => {
  const activeClass = isActive ? `sort__button--active` : ``;

  return (
    `<li>
      <a href="${type}" class="sort__button ${activeClass}">Sort by ${type}</a>
    </li>`
  );
};

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/filter-stats-view.js
> +const createFiltersAndStatsBar = (filters, isChecked) => {
@CheapSellsword 
`isChecked` удали из параметра

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/filter-stats-view.js
> +  const createFiltersTemplate = () => filters.map((filter) => {
@CheapSellsword 
Функцию `createFiltersTemplate` вынеси из функции `createFiltersAndStatsBar`.
В функцию `createFiltersTemplate` передавай 2 аргумента `filter`и `isChecked`.
Создай в функции `createFiltersAndStatsBar` константу, которую вставляй в `<div class="main-navigation__items">` вместо `${createFiltersTemplate()}`
В данной константе вызови метод map у передаваемого параметра `filters` и у каждого элемента вызывай функцию `createFiltersTemplate`

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/filter-stats-view.js
> +  #isChecked = null;
@CheapSellsword 
`#isChecked = null;` отсюда нужно удалить

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/filter-stats-view.js
> +    this.#isChecked = isChecked;
@CheapSellsword 
`this.#isChecked = isChecked;` отсюда нужно удалить

2021-12-07 22:48 UTC, NiyazGaripov commented on src/view/filter-stats-view.js
> +    return createFiltersAndStatsBar(this.#filters, this.#isChecked);
@CheapSellsword 
`this.#isChecked` отсюда нужно удалить

2021-12-09 16:49 UTC, CheapSellsword commented on src/main.js
>  const films = Array.from({length: GENERATED_FILMS_COUNT}, generateFilm);
Почему функция `generateFilm` здесь идёт без вызова?

2021-12-09 16:50 UTC, CheapSellsword commented on src/main.js
> +  const showMoreButton = mainElement.querySelector('.films-list__show-more');
// Почему, если `.films-list__show-more` искать селектором не в `mainElement`, а в `showMoreButtonComponent.element`, то консоль выдает
  Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at main.js:84
    at bundle.js:5605
    at bundle.js:5607

2021-12-09 16:51 UTC, CheapSellsword commented on src/main.js
> +  // Как сделать так, чтобы, при открытии попапа, закрывался уже открытый попап? Или это будет в следующих заданиях?
Как сделать так, чтобы, при открытии попапа, закрывался уже открытый попап? Или это будет в следующих заданиях?

2021-12-09 16:52 UTC, CheapSellsword commented on src/view/sort-view.js
>  const createSortItemTemplate = (type, isActive) => {
Не понимаю map

2021-12-09 19:32 UTC, NiyazGaripov commented on src/main.js
>  const films = Array.from({length: GENERATED_FILMS_COUNT}, generateFilm);
@CheapSellsword 
В данном случае используется интерфейс метода `from` глобального объекта `Array`.
С интерфейсом данного метода можешь ознакомиться [тут](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

Array.from() имеет необязательный параметр [mapFn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#parameters) - это callback функция
, благодаря этому параметру возможно выполнять метод `map` для каждого элемента создаваемого массива.

В JavaScript функции являются объектами высшего порядка. Это означает, что функции можно передавать в другие функции в виде параметров или возвращать в виде результата выполнения.

**Callback-функций** передаются в качестве параметров в другие функции и внутри неё вызываются.

Рассмотрим пример:
```
const hello = function () {
   return 'Hello, world!';
}

// Вызываем функцию
console.log(hello()); 
// В консоли выведется     Hello, world

// Выводим функцию в консоль без вызова
console.log(hello); 
// В консоли выведется    ƒ () { return 'Hello, world!'; }
```
В первом случае мы вызываем функцию hello при помощи круглых скобок и выводим результат выполнения в консоль. Во втором примере мы не делаем вызов функции (обрати внимание на отсутствие круглых скобок), и в консоль выводится содержимое функции. 
Выходит, нам ничего не мешает передать функцию в виде параметра в другую функцию. Чтобы когда потребуется вызывать переданную функцию.
```
const runInnerFunction = function (fn) {
  return fn();       // Вызываем функцию, переданную в качестве параметра в функцию runInnerFunction
}

console.log(runInnerFunction(hello)); // Hello, world
```

Таким образом, вызов `Array.from({length: GENERATED_FILMS_COUNT}, generateFilm);` эквивалентен цепочке `Array.from({length: GENERATED_FILMS_COUNT}).map(generateFilm)`

В метод `map` передаётся callback-функция `generateFilm`. И из примеров выше видно, что внутри метода `map` callback-функция `generateFilm` вызывается.

2021-12-09 20:38 UTC, NiyazGaripov commented on src/main.js
> +  // Как сделать так, чтобы, при открытии попапа, закрывался уже открытый попап? Или это будет в следующих заданиях?
@CheapSellsword 
Это будет в следующих заданиях.

2021-12-09 21:03 UTC, NiyazGaripov commented on src/view/sort-view.js
>  const createSortItemTemplate = (type, isActive) => {
@CheapSellsword 

Данная функция `const createSortTemplate = () => sortTypesArray.map((type) => createSortItemTemplate(type));` возвращает тебе массив с элементами сортировки.

`render(filtersAndStatsBar.element, filmSort.element, RenderPosition.AFTER_END);` - а вот тут ты рендеришь только первый элемент из созданного массива. Так как вызывая геттер `element` и в данном случае срабатывает вот эта строка `this.#element = createElement(this.template);`

Тебе нужно сохранить полученный массив с элементами сортировки и вставить в тег `<ul>`

```
const createSortTemplate = () => {
  const createSortList = sortTypesArray.map((sortElement, index) => createSortItemTemplate(sortElement, index === 0)).join('\n');

  return (
    `<ul class="sort">
        ${createSortList}
    </ul>`
  );
};

```
Обрати внимание на метод `join('\n')` и в качестве разделителя в метод передаётся символ перевода строки.
Если ты выведешь в консоль результат `sortTypesArray.map((sortElement, index) => createSortItemTemplate(sortElement, index === 0))`
то увидишь символ перевода строки. 
![Screenshot_20211209_235741](https://user-images.githubusercontent.com/24496044/145475066-f10550a3-07b4-4ed1-9fe8-afe522f9da2c.png)


Их нужно убрать при помощи метода [`join`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join)

2021-12-09 21:08 UTC, NiyazGaripov requested changes

2021-12-09 21:08 UTC, NiyazGaripov commented on src/view/sort-view.js
> +const sortTypesArray = [
@CheapSellsword 
В соответствии с критерием [Б9](https://up.htmlacademy.ru/ecmascript/16/criteries#b9) `Array` из названия нужно удалить. 

Название константы должны быть написаны прописными буквами [критерий Б5](https://up.htmlacademy.ru/ecmascript/16/criteries#b5)

2021-12-11 06:41 UTC, merged