Задание 4.1 и рефакторинг
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #8
Opened 2021-12-12 23:44 UTC by CheapSellsword

2021-12-13 19:00 UTC, NiyazGaripov requested changes

2021-12-14 19:28 UTC, CheapSellsword commented
> @CheapSellsword Касательно коммитов, делай коммиты атомарными. Один коммит — одна атомарная фича. Большие коммиты не эффективны, потому что сложно разбираться в коде, которого много. Поэтому в демо-репозиториях и реализованы коммиты с атомарноми фичами. Если бы на лекции разбирали один коммит со всеми изменениями было бы сложно это воспринимать. Ещё плюс в том, что можно откатиться к конкретному коммиту. А когда один большой коммит, да ещё с не информативным названием, есть большой шанс забыть в каком коммите реализован тот или иной функционал. [Пример](https://github.com/htmlacademy-ecmascript/taskmanager-16/pull/4) К размышлению: [Commit Guidelines](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines) [Как следует писать комментарии к коммитам](https://habr.com/ru/post/416887/) [Как правильно составлять описания коммитов и почему это важно](https://ru.hexlet.io/blog/posts/git-commit-message)

Спасибо за советы и ссылки, буду стараться правильно делать коммиты!

2021-12-14 21:04 UTC, NiyazGaripov commented on src/view/films-section-view.js
> +    <section class="most-commented films-list films-list--extra">
@CheapSellsword 
> Можно ли так делать? 

Нет. Тем более всё равно позже придём к тому, что не будем работать с DOM узлами напрямую.
> Если нет, то каким способом стоит выполнить этот пункт задания?

В целом у тебя хорошее, рабочее решение. На данном этапе достаточно искать по такому селектору `.films-list--extra:last-child`.

Т.е. вместо 
`const mostCommentedSection = filmsSectionComponent.element.querySelector('.most-commented');`
будет
`const mostCommentedSection = filmsSectionComponent.element.querySelector('.films-list--extra:last-child');`

2021-12-16 13:04 UTC, CheapSellsword commented on src/view/films-section-view.js
> +    <section class="most-commented films-list films-list--extra">
Понял, спасибо!

2021-12-16 18:05 UTC, NiyazGaripov requested changes

2021-12-16 19:41 UTC, merged