Module5 task1
htmlacademy-ecmascript/1827273-cinemaddict-16 pull request #9
Opened 2021-12-25 00:14 UTC by CheapSellsword

2021-12-25 00:46 UTC, CheapSellsword commented on src/presenter/collection-presenter.js
>    #mostCommentedFilmsContainer = this.#mostCommentedSection.querySelector('.films-list__container');
Как обойтись без поиска секций для отрисовки в них фильмов?

2021-12-25 00:46 UTC, CheapSellsword commented on src/presenter/collection-presenter.js
>        remove(prevPopup);
Не понятна схема с закрытием попапа:
    Как должна выглядеть эта функция?
    Почему она должна создаваться в главном презентере, где нет FilmPopupView, и передаваться в меньший презентер?
    Пункт задания "В презентере списка фильмов реализуйте метод для этого колбэка, который скроет попап, если таковой уже открыт." - как это реализовать и для какой ситуации?

2021-12-25 00:48 UTC, CheapSellsword commented on src/presenter/film-presenter.js
>        replace(this.#filmComponent, prevFilmComponent);
Пытаюсь сделать проверку на подобие проверки в лайве: this.#filmContainer.contains(prevFilmComponent**.element**), но выдаётся ошибка "Cannot read properties of null"?

2021-12-25 00:50 UTC, CheapSellsword commented on src/presenter/film-presenter.js
>      remove(prevPopupComponent);
В какой момент эти функции будут задействованы?

2021-12-25 00:50 UTC, CheapSellsword commented on src/presenter/film-presenter.js
>      this.#changeData({...this.#film, isFavorite: !this.#film.isFavorite});
Не понятен синтаксис этой функции

2021-12-25 00:51 UTC, CheapSellsword commented on src/utils/common.js
>      ...items.slice(index + 1),
Зачем здесь нужен spread operator, если 'items' и так массив?

2021-12-25 00:51 UTC, CheapSellsword commented on src/utils/common.js
>    if (index === -1) {
Для чего проверка на индекс '-1'?

2021-12-25 01:04 UTC, CheapSellsword commented
Не работает закрытие попапа при открытии нового, а также при клике по крестику. При открытии попапа выдаётся: 
`film-popup-view.js:172 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')`.

Не работают клики по кнопкам попапов и карточек фильмов. Ошибка: 
`Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.` 

Прощу прощения за большие коммиты. Пытался обойтись одним презентором изначально. Несколько раз всё переделывал, и с коммитами всё получилось запутанно.

2021-12-25 21:26 UTC, NiyazGaripov requested changes

2021-12-25 21:26 UTC, NiyazGaripov commented on src/presenter/film-presenter.js
>        replace(this.#filmComponent, prevFilmComponent);
@CheapSellsword 
`prevFilmComponent` в данном случае будет `null`, а у `null` нет геттера `element`.

В лайве использовался класс `#taskListContainer = new TaskListView(),`
У класса есть геттер  `element`.

В твоём случае  `this.#filmContainer` является DOM-элементом `<div class="films-list__container">`

2021-12-25 21:26 UTC, NiyazGaripov commented on src/presenter/film-presenter.js
>      remove(prevPopupComponent);
@CheapSellsword 
При каждом вызове метода `init` класса `FilmPresenter`

[Лекция начиная с 1:08:40](https://up.htmlacademy.ru/ecmascript/16/module/5/item/2)

2021-12-25 21:26 UTC, NiyazGaripov commented on src/utils/common.js
>    if (index === -1) {
@CheapSellsword 
Метод findIndex() возвращает индекс в массиве, если элемент удовлетворяет условию проверяющей функции. В противном случае возвращается -1.

`const index = items.findIndex((item) => item.id === update.id);` находим индекс фильма, у которого изменились данные. Если нету фильма, который обновился, тогда просто возвращаем все фильмы и ничего обновлять не нужно.

2021-12-25 21:26 UTC, NiyazGaripov commented on src/utils/common.js
>      ...items.slice(index + 1),
@CheapSellsword 
Тут собирается новый массив из имеющегося. 
Как писал выше, `index` - это индекс фильма,  у которого изменились данные.
 `...items.slice(0, index)` - в этой строке будут фильмы от 0 до фильма, у которого изменились данные.
`update,` - фильм, у которого изменились данные.
`...items.slice(index + 1), ` - в этой строке будут фильмы, следующие за фильмом, у которого изменились данные и до конца. 

Для понимания попробуй попрактиковаться с обычным массивом чисел

2021-12-25 21:26 UTC, NiyazGaripov commented on src/presenter/film-presenter.js
>      this.#changeData({...this.#film, isFavorite: !this.#film.isFavorite});
@CheapSellsword 
`this.#changeData` - это метод, который принимает в качестве аргумента объект с обновлёнными данными.
Т.е. это обычный вызов метода с аргументом.
Можешь тут поставить дебаггер и убедиться.

2021-12-25 21:34 UTC, NiyazGaripov commented
@CheapSellsword 

> Не работает закрытие попапа при открытии нового, а также при клике по крестику. При открытии попапа выдаётся:
film-popup-view.js:172 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener').
Не работают клики по кнопкам попапов и карточек фильмов. Ошибка:
Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
Прощу прощения за большие коммиты. Пытался обойтись одним презентором изначально. Несколько раз всё переделывал, и с коммитами всё получилось запутанно.


Это происходит из-за аналогичной ошибки https://github.com/htmlacademy-ecmascript/1827273-cinemaddict-16/pull/9#discussion_r775169865

у `null` нет метода `addEventListener`. Выводи в консоль либо вызывай деббагер в тех местах где происходят ошибки. 
[TypeError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2021-12-26 15:07 UTC, CheapSellsword commented on src/presenter/film-presenter.js
> +    // Проблема:
Проблема:
если в разных секциях отрисована одна и та же карточка фильма, то попап этого фильма не скрывается при клике на другую карточку, а при клике на такую же карточку дублируется

2021-12-26 19:00 UTC, CheapSellsword commented on src/view/sort-view.js
> +  setSortTypeChangeHandler = (callback) => {
И реализует подписку на изменение сортировки

2021-12-27 00:17 UTC, CheapSellsword commented
Не понимаю, как синхронизировать повторяющиеся карточки. У отрисованных более одного раза карточек и их попапов ломаются кнопки. Не получается исправить.

2021-12-27 14:16 UTC, NiyazGaripov commented on src/presenter/film-presenter.js
> +    // Проблема:
@CheapSellsword 
В демо-проекте нет повторяющихся задач. А в киномане есть повторяющиеся фильмы.
Ты пытаешься не идею, а код из демо-проекта полностью использовать для проекта киноман.
`#filmPresenter = new Map();` ты создаёшь Map.
`this.#filmPresenter.set(film.id, filmPresenter);` - тут записываешь в `#filmPresenter `  `{"id фильма" => FilmPresenter}`.
На странице у тебя будут фильмы повторяться, так как фильмы отображаются в разных секциях. Когда ты открываешь попап одного и того же фильма, у тебя происходит работа не с одним и тем же объектом, а с разными. Из-за этого для идентичного фильма  открывается новый попап. 
Из-за этого же ломаются кнопки. Так как происходит взаимодействие не с одним и тем же объектом, а с разными. 
Получается фильм в общей секции и этот же фильм, но в другой секции это не один и тот же объект, а разные.

Чтобы ты ещё больше не запутался, предлагаю сделать следующим образом.

1. Оставить только один презентор;
2. В рамках этого презентора реализовать методы из `FilmPresenter`
3. При клике на карточку фильма, для открытия попапа, в самом начале просто вызывать метод закрывающий попап. А он у тебя всегда один. 

В данном случае тебе не нужен mode, не нужно дополнительно синхронизировать одинаковые фильмы. У тебя один и тот же фильм будет одним объектом со своим текущим состоянием.

2021-12-27 14:22 UTC, NiyazGaripov commented on src/view/sort-view.js
> +  setSortTypeChangeHandler = (callback) => {
@CheapSellsword 
Не понял вопрос, раскрой пожалуйста.

2021-12-27 17:51 UTC, CheapSellsword commented on src/view/sort-view.js
> +  setSortTypeChangeHandler = (callback) => {
Это я так дополнил название коммита

2021-12-30 21:23 UTC, CheapSellsword commented on src/presenter/collection-presenter.js
> +    #presenters = [];
Вместо Map я сделал массив

2021-12-30 21:27 UTC, CheapSellsword commented on src/presenter/film-presenter.js
> +  #id = null;
Добавил id для контроля изменений во всех карточках.

2021-12-31 12:44 UTC, NiyazGaripov commented
@CheapSellsword
Отличная работа! Молодец!
Единственное, обрати внимание, что при повторном клике на карточку фильма, фильм повторно не открывается и на `bode` висит класс `hide-overflow`. Поправь в следующем задании

2021-12-31 12:46 UTC, merged

2021-12-31 12:46 UTC, NiyazGaripov approved these changes